[project]
name = "pinjected_localopenai"
version = "0.4.20a1"
description = "local openai bindings for pinjected library"
authors = [
    { name = "", email = "" }
]

dependencies = [
    "pinjected",
    "openai",
    "tiktoken",
    "injected-utils",
    "pydub",
    "pillow",
    "loguru",
    "pandas",
    "filelock",
    "reactivex>=4.0.4",
    "moviepy>=1.0.3",
]
readme = "README.md"
requires-python = ">=3.10"

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
